/**
 * Survey Management
 * ##Survey Management
 *
 * OpenAPI spec version: 4.0.0
 * Contact: techsupport@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {SurveyMapping} from './SurveyMapping';

export interface VisitMaster {
    id?: number;
    description?: string;
    visitType?: string;
    fromDate?: string;
    toDate?: string;
    visitGoal?: string;
    visitFrequency?: string;
    addBy?: string;
    addDate?: string;
    survey?: Array<SurveyMapping>;
}
