/**
 * CRM System API
 * CRM System API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: test@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Account} from './account';
import {Customer} from './customer';
import {Service} from './service';

/**
 * customer details
 */
export interface CustomerDetails {
    /**
     * request success or error specific code
     */
    code?: string;
    /**
     * Provides more information for when there was an error
     */
    message?: string;
    customer?: Customer;
    account?: Account;
    service?: Service;
}
