/**
 * Cash Register Management API
 * APIs to manage Cash Register
 *
 * OpenAPI spec version: 1.6.10
 * Contact: yagyawal.thakur@comviva.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import IHttpClient from '../../IHttpClient';
import { IAPIConfiguration } from '../../IAPIConfiguration';
import { Headers } from '../../Headers';
import HttpResponse from '../../HttpResponse';
import { LimitModification } from '../model/limitModification';
import MasterConfigService from '../../../services/master/api/MasterConfigService';
import HttpClient from '../../../services/HttpClient';
import IFilter from 'src/types/IFilter';

export default class LimitModificationService {
    masterService = new MasterConfigService();

    APIConfiguration: IAPIConfiguration;
    httpClient: IHttpClient;

    constructor() {
        this.APIConfiguration = {
            basePath: ''
        };
        try {
            this.masterService
                .getServiceUrl('CASH_REGISTER')
                .subscribe((url) => (this.APIConfiguration.basePath = url));
        } catch (e) {
            console.log('error while fetching cash register url', e);
        }
        this.httpClient = new HttpClient();
    }

    public createLimitModification(
        limitModification: LimitModification,
        observe?: 'body',
        headers?: Headers
    ): Observable<LimitModification>;
    public createLimitModification(
        limitModification: LimitModification,
        observe?: 'response',
        headers?: Headers
    ): Observable<HttpResponse<LimitModification>>;
    public createLimitModification(
        limitModification: LimitModification,
        observe: any = 'body',
        headers: Headers = {}
    ): Observable<any> {
        if (!limitModification) {
            throw new Error(
                'Required parameter register was null or undefined when calling createLimitModification.'
            );
        }

        headers['Accept'] = 'application/json;charset=utf-8';
        headers['Content-Type'] = 'application/json;charset=utf-8';

        const response: Observable<HttpResponse<LimitModification>> =
            this.httpClient.post(
                `${this.APIConfiguration.basePath}/limitIncreaseRequest`,
                limitModification as any,
                headers
            );
        if (observe === 'body') {
            return response.pipe(map((httpResponse) => httpResponse.response));
        }
        return response;
    }

    public deleteLimitModification(
        id: string,
        observe?: 'body',
        headers?: Headers
    ): Observable<LimitModification>;
    public deleteLimitModification(
        id: string,
        observe?: 'response',
        headers?: Headers
    ): Observable<HttpResponse<LimitModification>>;
    public deleteLimitModification(
        id: string,
        observe: any = 'body',
        headers: Headers = {}
    ): Observable<any> {
        if (!id) {
            throw new Error(
                'Required parameter id was null or undefined when calling limitIncreaseRequest.'
            );
        }

        headers['Accept'] = 'application/json;charset=utf-8';

        const response: Observable<HttpResponse<LimitModification>> =
            this.httpClient.delete(
                `${this.APIConfiguration.basePath
                }/limitIncreaseRequest/${encodeURIComponent(
                    String(id)
                )}` as any,
                headers
            );
        if (observe === 'body') {
            return response.pipe(map((httpResponse) => httpResponse.response));
        }
        return response;
    }

    public getLimitIncreaseRequest(
        id: string,
        observe?: 'body',
        headers?: Headers
    ): Observable<Array<LimitModification>>;
    public getLimitIncreaseRequest(
        id: string,
        observe?: 'response',
        headers?: Headers
    ): Observable<HttpResponse<Array<LimitModification>>>;
    public getLimitIncreaseRequest(
        id: string,
        observe: any = 'body',
        headers: Headers = {}
    ): Observable<any> {
        if (!id) {
            throw new Error(
                'Required parameter id was null or undefined when calling getLimitModificationRequest.'
            );
        }

        headers['Accept'] = 'application/json;charset=utf-8';

        const response: Observable<HttpResponse<Array<LimitModification>>> =
            this.httpClient.get(
                `${this.APIConfiguration.basePath
                }/limitIncreaseRequest/${encodeURIComponent(
                    String(id)
                )}` as any,
                headers
            );
        if (observe === 'body') {
            return response.pipe(map((httpResponse) => httpResponse.response));
        }
        return response;
    }

    public listLimitIncreaseRequests(
        fields?: string,
        offset?: number,
        limit?: number,
        observe?: 'body',
        headers?: Headers,
        filter?: any
    ): Observable<Array<LimitModification>>;
    public listLimitIncreaseRequests(
        fields?: string,
        offset?: number,
        limit?: number,
        observe?: 'response',
        headers?: Headers,
        filter?: any
    ): Observable<HttpResponse<Array<LimitModification>>>;
    public listLimitIncreaseRequests(
        fields?: string,
        offset?: number,
        limit?: number,
        observe: any = 'body',
        headers: Headers = {},
        filter?: any
    ): Observable<any> {
        let queryParameters: string[] = [];
        if (fields !== undefined) {
            queryParameters.push(
                'fields=' + encodeURIComponent(String(fields))
            );
        }
        if (filter != undefined) {
            filter.forEach((filter: IFilter) => {
                queryParameters.push(
                    `${filter.key}${filter.operator === 'eq' ? '*=' : filter.operator
                    }${encodeURIComponent(String(filter.value))}`
                );
            });
        }
        if (offset !== undefined) {
            queryParameters.push(
                'offset=' + encodeURIComponent(String(offset))
            );
        }
        if (limit !== undefined) {
            queryParameters.push('limit=' + encodeURIComponent(String(limit)));
        }

        headers['Accept'] = 'application/json;charset=utf-8';

        const response: Observable<HttpResponse<Array<LimitModification>>> =
            this.httpClient.get(
                `${this.APIConfiguration.basePath
                }/limitIncreaseRequest?sort=-requestDate&${queryParameters.join(
                    '&'
                )}` as any,
                headers
            );
        if (observe === 'body') {
            return response.pipe(map((httpResponse) => httpResponse.response));
        }
        return response;
    }

    public updateLimitIncreaseRequest(
        id: string,
        limitModification: LimitModification,
        observe?: 'body',
        headers?: Headers
    ): Observable<LimitModification>;
    public updateLimitIncreaseRequest(
        id: string,
        limitModification: LimitModification,
        observe?: 'response',
        headers?: Headers
    ): Observable<HttpResponse<LimitModification>>;
    public updateLimitIncreaseRequest(
        id: string,
        limitModification: LimitModification,
        observe: any = 'body',
        headers: Headers = {}
    ): Observable<any> {
        if (!id) {
            throw new Error(
                'Required parameter id was null or undefined when calling updateLimitModificationRequest.'
            );
        }

        if (!limitModification) {
            throw new Error(
                'Required parameter register was null or undefined when calling updateLimitModificationRequest.'
            );
        }

        headers['Accept'] = 'application/json;charset=utf-8';
        headers['Content-Type'] = 'application/json;charset=utf-8';

        const response: Observable<HttpResponse<LimitModification>> =
            this.httpClient.patch(
                `${this.APIConfiguration.basePath
                }/limitIncreaseRequest/${encodeURIComponent(
                    String(id)
                )}`,
                limitModification as any,
                headers
            );
        if (observe === 'body') {
            return response.pipe(map((httpResponse) => httpResponse.response));
        }
        return response;
    }

}