/**
 *
 *
 *
 *
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Inventory details.
 */
export interface InventoryDetail {
    /**
     * SKU id from erp.
     */
    skuId: any;
    /**
     *
     * Product offering Id from product catalog.
     */
    productOfferingId: string;
    /**
     * inventory start serial number.
     */
    inventoryStartSerialNumber?: string;

    addType?: string;

    quantity?: string;
    /**
     * inventory end serial number.
     */
    inventoryEndSerialNumber?: string;
    /**
     * Inventory current status.
     */
    status: string;
    /**
     * Inventory's current Location Type Description.
     */
    currentLocationType?: string;
    /**
     * Inventory's current Location ID.
     */
    currentLocation?: string;
    /**
     * inventory addition date.
     */
    addDate?: Date;
    /**
     * Number of days in which inventory get expired.
     */
    warrantyDuration?: string;
    /**
     * Warranty expiration date of inventory.
     */
    warrantyExpirationDate?: Date;
    /**
     * Secondary details  description of inventory.
     */
    secondaryDescription?: string;
    /**
     * Secondary Details of inventory.
     */
    secondaryValue?: string;
    /**
     * Serial No of Bundle of Inventory in box.
     */
    boxSerialNumber?: string;
    /**
     * Condition of Inventory.
     */
    inventoryCondition?: string;
    /**
     * Activation Date of Inventory.
     */
    activationDate?: Date;
}
