/**
 * Inventory Management API
 * API for Inventory Management
 *
 * OpenAPI spec version: 1.0.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {InventoryBatch} from './inventoryBatch';
import {ItemTotalPrice} from './itemTotalPrice';

/**
 * Inventory transfer.
 */
export interface InventoryTransfer {
    /**
     * Delivery Person Name.
     */
    deliveryPerson?: string;
    /**
     * Inventory Transfer for dispatch medium.
     */
    dispatchMedium?: string;
    /**
     * Inventory transfer source ID.
     */
    sourceId?: string;
    /**
     * Inventory transfer destination ID.
     */
    destinationId?: string;
    /**
     * Inventory transfer batch list
     */
    batchList?: Array<InventoryBatch>;
    /**
     * Inventory Transfer purchase order number.
     */
    /**
     * Grn Number of parent.
     */
    parentGrn?: string;
    /**
     * Message for rejection of inventory Transfer
     */
    rejectionReason?: string;
    /**
     * Message note after inventory transfer
     */
    remarks?: string;

    productId?: string;
    skuId?: string;

    productName?: string;

    description?: string;

    batchNo?: string;

    inventoryTypeId?: number;

    serialized?: boolean;

    productOfferingId?: string;

    unitType?: number;

    SerialType?: string;

    startSerial?: string;

    endSerial?: string;

    quantity?: number;

    inventoryCount?: number;

    allocatedQuantity?: number;

    bundleId?: number;

    lineNumber?: number;

    bundleSerialNo?: number;

    transferTypeId?: number;

    sourceLocationId?: string;

    targetLocationId?: string;

    orderMode?: string;

    serialType?: string;

    serialNumbers?: Array<any>;

    dashboardRequestedQuantity?: Array<InventoryBatch>;

    lineItems?: Array<InventoryBatch>;

    itemTotalPrice?: ItemTotalPrice;
}
