/**
 * API Party
 * ## TMF API Reference : TMF 666 - Party   ### Release : 19.0
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {AccountBalance} from './accountBalance';
import {Money} from './money';
/**
 * Describes a given characteristic of an object or entity through a name/value pair.
 */
export interface BankAccountInformation {
    /**
     * id
     */
    id?: string;

    partnerId?: string;
    /**
     * Name of the account
     */
    name?: string;
    /**
     * Account type
     */
    accountType?: string;
    /**
     * Description of the account
     */
    accountNumber?: number;
    /**
     * Account number of account
     */
    bankName?: string;
    /**
     * Name of the bank
     */
    branch?: string;
    /**
     * branch of account
     */
    bankCode?: string;
    /**
     * bank code of account
     */
    description?: string;
    /**
     * Payment status of user
     */
    paymentStatus?: string;
    /**
     * status of the account
     */
    state?: string;

    '@type'?: string;

    accountBalance?: Array<AccountBalance>;

    creditLimit?: Money;
}
