/**
 *
 *
 *
 *
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Observable} from 'rxjs';
import {map} from 'rxjs/operators';
import IHttpClient from '../../IHttpClient';
import {IAPIConfiguration} from '../../IAPIConfiguration';
import {Headers} from '../../Headers';
import HttpResponse from '../../HttpResponse';
import HttpClient from '../../HttpClient';
import MasterConfigService from '../../master/api/MasterConfigService';
import IFilter from '../../../types/IFilter';

/* eslint-disable no-param-reassign */

export default class StockAuditService {
    APIConfiguration: IAPIConfiguration;

    masterService = new MasterConfigService();

    httpClient: IHttpClient;

    constructor() {
        this.APIConfiguration = {
            // basePath: 'http://172.16.10.94:9500/api/v1'
            basePath: '',
            partyManagementUrl: ''
        };
        try {
            this.masterService
                .getServiceUrl('INVENTORY_DETAILS_URL')
                .subscribe((url) => (this.APIConfiguration.basePath = url));
            this.masterService
                .getServiceUrl('INDIVIDUAL_URL')
                .subscribe(
                    (url) => (this.APIConfiguration.partyManagementUrl = url)
                );
        } catch (e) {
            console.log('error while fetching inventory details url', e);
        }
        this.httpClient = new HttpClient();
    }

    /**
     * Get customer information for a given accountID
     * Get customer information for a given accountID
     * @param serviceID Get customer information for a given accountID
     @param queryString
     @param headers
     */

    public getAuditorName(
        queryString: string,
        observe: any = 'body',
        headers: Headers = {}
    ): Observable<any> {
        headers.Accept = 'application/json;charset=utf-8';
        headers['x-auth-token'] =
            'VQ/ZK9+z2gzgTOm1ZnMyn0Ev6byXWPqWgsj1TrbN74c=';
        const response: Observable<HttpResponse<any>> = this.httpClient.get(
            `${this.APIConfiguration.partyManagementUrl}/${queryString}`,
            headers
        );
        return response.pipe(map((d) => d.response));
    }

    public getAllStock(
        observe: any = 'body',
        headers: Headers = {},
        offset?: number,
        limit?: number,
        filters?: any
    ): Observable<any> {
        const queryParameters: string[] = [];

        if (filters != undefined) {
            filters.forEach((filter: IFilter) => {
                queryParameters.push(
                    `${filter.key}${
                        filter.operator === 'eq' ? '*=' : filter.operator
                    }${encodeURIComponent(String(filter.value))}`
                );
            });
        }
        if (offset !== undefined) {
            queryParameters.push(
                `offset=${encodeURIComponent(String(offset))}`
            );
        }
        if (limit !== undefined) {
            queryParameters.push(`limit=${encodeURIComponent(String(limit))}`);
        }

        headers.Accept = 'application/json;charset=utf-8';
        headers['x-auth-token'] =
            'VQ/ZK9+z2gzgTOm1ZnMyn0Ev6byXWPqWgsj1TrbN74c=';
        const response: Observable<HttpResponse<any>> = this.httpClient.get(
            `${
                this.APIConfiguration.basePath
            }/stockAudit?${queryParameters.join('&')}` as any,
            headers
        );
        return response.pipe(map((d) => d.response));
    }

    public submitStock(
        body: any,
        observe: any = 'body',
        headers: Headers = {}
    ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error(
                'Required parameter body was null or undefined when calling createInventory.'
            );
        }

        headers.Accept = 'application/json;charset=utf-8';
        headers['x-auth-token'] =
            'VQ/ZK9+z2gzgTOm1ZnMyn0Ev6byXWPqWgsj1TrbN74c=';
        const response: Observable<HttpResponse<any>> = this.httpClient.post(
            `${this.APIConfiguration.basePath}/stockAudit`,
            body,
            headers
        );
        return response.pipe(map((d) => d.response));
    }

    editStock(
        stockID: string,
        body: any,
        observe: any = 'body',
        headers: Headers = {}
    ): Observable<any> {
        if (!stockID) {
            throw new Error(
                'Required parameter id was null or undefined when calling delete stock.'
            );
        }

        headers.Accept = 'application/json;charset=utf-8';

        const response: Observable<HttpResponse<any>> = this.httpClient.put(
            `${this.APIConfiguration.basePath}/stockAudit/${stockID}`,
            body,
            headers
        );
        if (observe === 'body') {
            return response.pipe(map((httpResponse) => httpResponse.response));
        }
        return response;
    }

    getProductDetails(
        stockID: string,
        observe: any = 'body',
        headers: Headers = {}
    ): Observable<any> {
        if (!stockID) {
            throw new Error(
                'Required parameter id was null or undefined when calling delete stock.'
            );
        }

        headers.Accept = 'application/json;charset=utf-8';

        const response: Observable<HttpResponse<any>> = this.httpClient.get(
            `${this.APIConfiguration.basePath}/stockAudit/${stockID}`,
            headers
        );
        if (observe === 'body') {
            return response.pipe(map((httpResponse) => httpResponse.response));
        }
        return response;
    }

    deleteStock(
        stockID: string,
        observe: any = 'body',
        headers: Headers = {}
    ): Observable<any> {
        if (!stockID) {
            throw new Error(
                'Required parameter id was null or undefined when calling delete stock.'
            );
        }

        headers.Accept = 'application/json;charset=utf-8';

        const response: Observable<HttpResponse<any>> = this.httpClient.delete(
            `${this.APIConfiguration.basePath}/stockAudit/${stockID}`,
            headers
        );
        if (observe === 'body') {
            return response.pipe(map((httpResponse) => httpResponse.response));
        }
        return response;
    }
}
