/**
 * snd-commission-management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CommissionMaster {
    commissionId?: number;
    comissionName?: string;
    statusText?: string;
    walletName?: string;
    description?: string;
    commissionCode?: string;
    active?: string;
    commissionAmount?: number;
    startDate?: string;
    endDate?: string;
    sourceMsisdn?: string;
    erpInventoryId?: string;
    templateConf?: string;
    skuId?: string;
}
