/**
 * API CustomerBill
 * ## TMF API Reference: TMF 678 - Customer bill Management  ### Release: 19.5 - December 2019  The Customer Bill Management API allows to find and retrieve one or several customer bills (also called invoices) produced for a customer. A customer bill is an electronic or paper document produced at the end of the billing process. The customer bill gathers and displays different items (applied customer billing rates generated during the rating and billing processes) to be charged to a customer. It represents a total amount due for all the products during the billing period and all significant information like dates, bill reference... This API provides also operations to find and retrieve the details of applied customer billing rates presented on a customer bill.  Finally, this API allows to request in real-time a customer bill creation and to manage this request.  ### Resources  - customerBill - appliedCustomerBillingRate - customerBillOnDemand - billingCycle  ### Operations Customer Bill Management API performs the following operations : - Retrieve a customer bill or a collection of customer bills depending on filter criteria. - Partial update of  a customer bill (for administration purposes). -  Retrieve an applied customer billing rate or a collection of applied customer billing rates depending on filter criteria. -  Create a customer bill on demand request, retrieve one or a collection of  customer bill on demand request(s) depending on filter criteria.  - Manage notification of events on customer bill and customer bill on demand.  Copyright © TM Forum 2018. All Rights Reserved.
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Observable} from 'rxjs';
import {map} from 'rxjs/operators';
import IHttpClient from '../../IHttpClient';
import {IAPIConfiguration} from '../../IAPIConfiguration';
import {Headers} from '../../Headers';
import HttpResponse from '../../HttpResponse';
import HttpClient from '../../HttpClient';
import MasterConfigService from '../../master/api/MasterConfigService';
import {CustomerBillOnDemand} from '../model/customerBillOnDemand';
import {CustomerBillOnDemandCreate} from '../model/customerBillOnDemandCreate';

export default class CustomerBillOnDemandService {
    APIConfiguration: IAPIConfiguration;

    masterService = new MasterConfigService();

    httpClient: IHttpClient;

    constructor() {
        this.APIConfiguration = {
            // basePath: 'http://172.30.35.130:9876'
            basePath: ''
        };
        try {
            this.masterService
                .getServiceUrl('CUSTOMER_BILL_URL')
                .subscribe((url) => (this.APIConfiguration.basePath = url));
        } catch (e) {
            console.log('error while fetching basepath url', e);
        }
        this.httpClient = new HttpClient();
    }

    /**
     * Creates a CustomerBillOnDemand
     * This operation creates a CustomerBillOnDemand entity.
     * @param customerBillOnDemand The CustomerBillOnDemand to be created
     
     */
    public createCustomerBillOnDemand(
        customerBillOnDemand: CustomerBillOnDemandCreate,
        observe?: 'body',
        headers?: Headers
    ): Observable<CustomerBillOnDemand>;
    public createCustomerBillOnDemand(
        customerBillOnDemand: CustomerBillOnDemandCreate,
        observe?: 'response',
        headers?: Headers
    ): Observable<HttpResponse<CustomerBillOnDemand>>;
    public createCustomerBillOnDemand(
        customerBillOnDemand: CustomerBillOnDemandCreate,
        observe: any = 'body',
        headers: Headers = {}
    ): Observable<any> {
        if (!customerBillOnDemand) {
            throw new Error(
                'Required parameter customerBillOnDemand was null or undefined when calling createCustomerBillOnDemand.'
            );
        }

        headers['Accept'] = 'application/json;charset=utf-8';
        headers['Content-Type'] = 'application/json;charset=utf-8';

        const response: Observable<HttpResponse<CustomerBillOnDemand>> =
            this.httpClient.post(
                `${this.APIConfiguration.basePath}/customerBillOnDemand`,
                customerBillOnDemand as any,
                headers
            );
        if (observe === 'body') {
            return response.pipe(map((httpResponse) => httpResponse.response));
        }
        return response;
    }

    /**
     * List or find CustomerBillOnDemand objects
     * This operation list or find CustomerBillOnDemand entities
     * @param fields Comma-separated properties to be provided in response
     * @param offset Requested index for start of resources to be provided in response
     * @param limit Requested number of resources to be provided in response
     
     */
    public listCustomerBillOnDemand(
        fields?: string,
        offset?: number,
        limit?: number,
        observe?: 'body',
        headers?: Headers
    ): Observable<Array<CustomerBillOnDemand>>;
    public listCustomerBillOnDemand(
        fields?: string,
        offset?: number,
        limit?: number,
        observe?: 'response',
        headers?: Headers
    ): Observable<HttpResponse<Array<CustomerBillOnDemand>>>;
    public listCustomerBillOnDemand(
        fields?: string,
        offset?: number,
        limit?: number,
        observe: any = 'body',
        headers: Headers = {}
    ): Observable<any> {
        let queryParameters: string[] = [];
        if (fields !== undefined) {
            queryParameters.push(
                'fields=' + encodeURIComponent(String(fields))
            );
        }
        if (offset !== undefined) {
            queryParameters.push(
                'offset=' + encodeURIComponent(String(offset))
            );
        }
        if (limit !== undefined) {
            queryParameters.push('limit=' + encodeURIComponent(String(limit)));
        }

        headers['Accept'] = 'application/json;charset=utf-8';

        const response: Observable<HttpResponse<Array<CustomerBillOnDemand>>> =
            this.httpClient.get(
                `${
                    this.APIConfiguration.basePath
                }/customerBillOnDemand?${queryParameters.join('&')}` as any,
                headers
            );
        if (observe === 'body') {
            return response.pipe(map((httpResponse) => httpResponse.response));
        }
        return response;
    }

    /**
     * Retrieves a CustomerBillOnDemand by ID
     * This operation retrieves a CustomerBillOnDemand entity. Attribute selection is enabled for all first level attributes.
     * @param id Identifier of the CustomerBillOnDemand
     * @param fields Comma-separated properties to provide in response
     
     */
    public retrieveCustomerBillOnDemand(
        id: string,
        fields?: string,
        observe?: 'body',
        headers?: Headers
    ): Observable<CustomerBillOnDemand>;
    public retrieveCustomerBillOnDemand(
        id: string,
        fields?: string,
        observe?: 'response',
        headers?: Headers
    ): Observable<HttpResponse<CustomerBillOnDemand>>;
    public retrieveCustomerBillOnDemand(
        id: string,
        fields?: string,
        observe: any = 'body',
        headers: Headers = {}
    ): Observable<any> {
        if (!id) {
            throw new Error(
                'Required parameter id was null or undefined when calling retrieveCustomerBillOnDemand.'
            );
        }

        let queryParameters: string[] = [];
        if (fields !== undefined) {
            queryParameters.push(
                'fields=' + encodeURIComponent(String(fields))
            );
        }

        headers['Accept'] = 'application/json;charset=utf-8';

        const response: Observable<HttpResponse<CustomerBillOnDemand>> =
            this.httpClient.get(
                `${
                    this.APIConfiguration.basePath
                }/customerBillOnDemand/${encodeURIComponent(
                    String(id)
                )}?${queryParameters.join('&')}` as any,
                headers
            );
        if (observe === 'body') {
            return response.pipe(map((httpResponse) => httpResponse.response));
        }
        return response;
    }
}
