/**
 * Product Catalog Management
 * ## TMF API Reference: TMF620 - Product Catalog Management  ### Release : 20.5 - March 2021  Product Catalog API is one of Catalog Management API Family. Product Catalog API goal is to provide a catalog of products.   ### Operations Product Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * OpenAPI spec version: 4.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {TimePeriod} from './timePeriod';

/**
 * This class defines a characteristic specification.
 */
export interface CharacteristicSpecificationBase {
    /**
     * Unique ID for the characteristic
     */
    id?: string;
    /**
     * If true, the Boolean indicates that the target Characteristic is configurable
     */
    configurable?: boolean;
    /**
     * A narrative that explains the CharacteristicSpecification.
     */
    description?: string;
    /**
     * An indicator that specifies that the values for the characteristic can be extended by adding new values when instantiating a characteristic for a resource.
     */
    extensible?: boolean;
    /**
     * An indicator that specifies if a value is unique for the specification. Possible values are; \"unique while value is in effect\" and \"unique whether value is in effect or not\"
     */
    isUnique?: boolean;
    /**
     * The maximum number of instances a CharacteristicValue can take on. For example, zero to five phone numbers in a group calling plan, where five is the value for the maxCardinality.
     */
    maxCardinality?: number;
    /**
     * The minimum number of instances a CharacteristicValue can take on. For example, zero to five phone numbers in a group calling plan, where zero is the value for the minCardinality.
     */
    minCardinality?: number;
    /**
     * A word, term, or phrase by which this characteristic specification is known and distinguished from other characteristic specifications.
     */
    name?: string;
    /**
     * A rule or principle represented in regular expression used to derive the value of a characteristic value.
     */
    regex?: string;
    /**
     * A kind of value that the characteristic can take on, such as numeric, text and so forth
     */
    valueType?: string;
    /**
     * The period of time for which a characteristic is applicable.
     */
    validFor?: TimePeriod;
    /**
     * When sub-classing, this defines the super-class
     */
    baseType?: string;
    /**
     * A URI to a JSON-Schema file that defines additional attributes and relationships
     */
    schemaLocation?: string;
    /**
     * When sub-classing, this defines the sub-class Extensible name
     */
    type?: string;
    /**
     * This (optional) field provides a link to the schema describing the value type.
     */
    valueSchemaLocation?: string;
}
