/**
 * Product Catalog Management
 * ## TMF API Reference: TMF620 - Product Catalog Management  ### Release : 20.5 - March 2021  Product Catalog API is one of Catalog Management API Family. Product Catalog API goal is to provide a catalog of products.   ### Operations Product Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * OpenAPI spec version: 4.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {JobStateType} from './jobStateType';

/**
 * Represents a task used to import resources from a file Skipped properties: id,href
 */
export interface ImportJobCreate {
    /**
     * Date at which the job was completed
     */
    completionDate?: Date;
    /**
     * Indicates the format of the imported data
     */
    contentType?: string;
    /**
     * Date at which the job was created
     */
    creationDate?: Date;
    /**
     * Reason for failure if status is failed
     */
    errorLog?: string;
    /**
     * URL of the root resource where the content of the file specified by the import job must be applied
     */
    path?: string;
    /**
     * URL of the file containing the data to be imported
     */
    url: string;
    /**
     * Status of the import job (not started, running, succeeded, failed)
     */
    status?: JobStateType;
    /**
     * When sub-classing, this defines the super-class
     */
    baseType?: string;
    /**
     * A URI to a JSON-Schema file that defines additional attributes and relationships
     */
    schemaLocation?: string;
    /**
     * When sub-classing, this defines the sub-class Extensible name
     */
    type?: string;
}
