/**
 * Product Catalog Management
 * ## TMF API Reference: TMF620 - Product Catalog Management  ### Release : 20.5 - March 2021  Product Catalog API is one of Catalog Management API Family. Product Catalog API goal is to provide a catalog of products.   ### Operations Product Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * OpenAPI spec version: 4.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Money} from './money';

/**
 * Provides all amounts (tax included, duty free, tax rate), used currency and percentage to apply for Price Alteration.
 */
export interface ProductPriceValue {
    /**
     * Percentage to apply for ProdOfferPriceAlteration
     */
    percentage?: number;
    /**
     * Tax category
     */
    taxCategory?: string;
    /**
     * Tax rate
     */
    taxRate?: number;

    taxAmount?: number;
    /**
     * All taxes excluded amount (expressed in the given currency)
     */
    dutyFreeAmount?: Money;
    /**
     * All taxes included amount (expressed in the given currency)
     */
    taxIncludedAmount?: Money;
    /**
     * When sub-classing, this defines the super-class
     */
    baseType?: string;
    /**
     * A URI to a JSON-Schema file that defines additional attributes and relationships
     */
    schemaLocation?: string;
    /**
     * When sub-classing, this defines the sub-class Extensible name
     */
    type?: string;
}
