/**
 * Survey Management
 * ##Survey Management
 *
 * OpenAPI spec version: 4.0.0
 * Contact: techsupport@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SurveyMapping {
    surveyType?: number;
    surveyDescription?: string;
    fromDate?: string;
    toDate?: string;
}
