/**
 * Survey Management
 * ##Survey Management
 *
 * OpenAPI spec version: 4.0.0
 * Contact: techsupport@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {SiteMapping} from './SiteMapping';

export interface VisitBatch {
    id?: number;
    visitId?: number;
    givenName?: string;
    visit?: string;
    addBy?: string;
    addDate?: string;
    fromDate?: string;
    toDate?: string;
    site?: Array<SiteMapping>;
    surveyorUserId?: string;
}

export interface Zones {
    zoneDesc: string;
    zoneId: string;
    hubList: any;
    areaList: any;
    routeList: any;
}
