/**
 * Customer Order Management
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5.4.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface OrderAcknowledgementRef {
    /**
     * Unique order id generated by COM
     */
    orderId: string;
    /**
     * unique request id
     */
    requestId?: string;
}
