/**
 * Customer Order Management
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 5.4.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PaymentDetailRef {
    /**
     * Mode in which the payment is done.possible values - [1-CC,2-DC,3-Cheque,4-DD,6-Cash,7-tax-certificate]
     */
    paymentMode: string;
    /**
     * external reference number if any
     */
    referenceExternalId?: string;
    /**
     * amount paid through this mode
     */
    amountPaid: string;
    /**
     * card Number Mandatory for payment Mode 1|2
     */
    cardNumber?: string;
    /**
     * cheque Number. Mandatory for payment mode 3
     */
    chequeNo?: string;
    /**
     * DD Number Mandatory for payment mode 4
     */
    ddNo?: string;
    /**
     * cheque date. Mandatory for payment mode 3
     */
    chequeDate?: Date;
    /**
     * certificate Number Mandatory for payment Mode 7
     */
    certificateNumber?: string;
}
