/**
 * Trouble Ticket
 * This is Swagger UI environment generated for the TMF Trouble Ticket specification
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {TimePeriod} from './timePeriod';

/**
 * Attachment refers to extensions or additional parts that is or may be attached to something (agreements, contracts, appointments) to perform a particular function. They can be communication attachments, documents and other.
 */
export interface Attachment {
    /**
     * Identifier of the binary attachment
     */
    id?: string;
    /**
     * Reference of the attached document
     */
    href?: string;
    /**
     * The size in Bytes of the of the document or attachment. If this component contains the embedded data then the size is the size of the embedded data; if it is a reference without the data then it is the size of the referenced document.
     */
    size?: number;
    /**
     * name of the binary attachment
     */
    name?: string;
    /**
     * the description of the binary attachment
     */
    description?: string;
    /**
     * The unit of measure for the size
     */
    sizeUnit?: string;
    /**
     * mimeType of the Attachement ( e,g application/pdf)
     */
    mimeType?: string;
    /**
     * URL of the Attachment
     */
    url?: string;
    /**
     * validity period of the Attachment
     */
    validFor?: TimePeriod;
    /**
     * Indicates the (class) type of the attachment.
     */
    type?: string;
}
