/**
 * Trouble Ticket
 * This is Swagger UI environment generated for the TMF Trouble Ticket specification
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Holds the status notification reasons and associated date the status changed, populated by the server
 */
export interface StatusChange {
    /**
     * The status of the trouble ticket
     */
    status?: string;
    /**
     * The reason why the status changed.
     */
    changeReason?: string;
    /**
     * The date and time the status changed.
     */
    changeDate?: Date;
    /**
     * Indicates the (class) type of statusChange
     */
    type?: string;
}
