/**
 * Trouble Ticket
 * This is Swagger UI environment generated for the TMF Trouble Ticket specification
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TimePeriod {
    startDateTime?: Date;
    endDateTime?: Date;
}
