/**
 * snd-commission-management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CommissionSlab {
    id?: number;
    inventiveId?: number;
    incentiveType?: string;
    targetCriteriaId?: number;
    inventiveAmount?: number;
    fromRange: number;
    toRange: number;
    value?: number;
}
