/**
 * snd-commission-management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {CommissionSlab} from './commissionSlab';

export interface CommissionIncentive {
    id?: number;
    planId?: number;
    ruleId?: number;
    versionNo?: number;
    isActive?: string;
    name?: string;
    inventiveId?: number;
    incentiveType?: string;
    targetCriteriaId?: number;
    targetCriteriaDesc?: string;
    inventiveAmount?: number;
    fromDate?: string;
    toDate?: string;
    slabs?: Array<CommissionSlab>;
    slabType?: string;
}
