/**
 * Account Management
 * This is Swagger UI environment generated for the TMF Account Management specification
 *
 * OpenAPI spec version: 2.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Money} from './money';
import {TimePeriod} from './timePeriod';

/**
 * Balances linked to the account
 */
export interface AccountBalance {
    /**
     * Generic attribute indicating the base class type of the extension class of the current object. Useful only when the class type of the current  object is unknown to the implementation.
     */
    baseType?: string;
    /**
     * Generic attribute containing the link to the schema that defines the structure of the class type of the current object.
     */
    schemaLocation?: string;
    /**
     * Generic attribute containing the name of the resource class type
     */
    balanceType?: string;
    /**
     * Balance amount
     */
    amount?: Money;
    /**
     * Type of the balance : deposit balance, disputed balance, loyalty balance, receivable balance...
     */
    '@type'?: string;
    /**
     * Balance validity period
     */
    validFor?: TimePeriod;
    /**
     * serial number of the sim
     */
    simSerialNo?: string;
    /**
     * mobile number of the account user
     */
    mobileNo?: number;
    /**
     * status of the account
     */
    state?: string;
}
