/**
 * Trouble Ticket
 * This is Swagger UI environment generated for the TMF Trouble Ticket specification
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * RelatedParty reference. A related party defines party or party role linked to a specific entity.
 */
export interface RelatedPartyRef {
    /**
     * Unique identifier of a related party
     */
    id?: string;
    /**
     * Reference of the related party, could be a party reference or a party role reference
     */
    href?: string;
    /**
     * Role of the related party.
     */
    role?: string;
    /**
     * Name of the related party
     */
    name?: string;
    /**
     * A string. Indicates the type (class) of related party. For example, Organization or Individual (if party), Customer, Supplier, etc. (if party role).
     */
    referredType?: string;
}
