/**
 * Trouble Ticket
 * This is Swagger UI environment generated for the TMF Trouble Ticket specification
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Represents a relationship between trouble tickets
 */
export interface TicketRelationship {
    /**
     * Unique identifier of the related trouble ticket
     */
    id?: string;
    /**
     * Hyperlink, a reference to the related trouble ticket entity
     */
    href?: string;
    /**
     * Type of the trouble ticket relationship can be isChiled, dependent etc...
     */
    type?: string;
}
