/**
 * snd-commission-management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface EventsDetails {
    eventId?: string;
    eventType?: string;
    eventSubType?: string;
    eventDate?: string;
    loadDate?: string;
    fileName?: string;
    amount?: number;
    duration?: number;
    units?: number;
    msisdn?: string;
    sim?: string;
    partnerId?: string;
    id?: number;
    critTId?: string;
}
