/**
 * snd-commission-management API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SalesChannelTarget {
    id?: number;
    activationTarget?: number;
    addBy?: string;
    addDate?: string;
    cycleType?: number;
    modBy?: string;
    modDate?: string;
    targetName?: string;
    salesChannel?: string;
    salesChannelId?: number;
    targetMonth?: string;
    targetType?: number;
    targetStartDate?: string;
    targetEndDate?: string;
}
