/**
 * API Party
 * ## TMF API Reference : TMF 632 - Party   ### Release : 19.0   The party API provides standardized mechanism for party management such as creation, update, retrieval, deletion and notification of events. Party can be an individual or an organization that has any kind of relation with the enterprise. Party is created to record individual or organization information before the assignment of any role. For example, within the context of a split billing mechanism, Party API allows creation of the individual or organization that will play the role of 3 rd payer for a given offer and, then, allows consultation or update of his information.  ### Resources - Organization - Individual - Hub  Party API performs the following operations : - Retrieve an organization or an individual - Retrieve a collection of organizations or individuals according to given criteria - Create a new organization or a new individual - Update an existing organization or an existing individual - Delete an existing organization or an existing individual - Notify events on organizatin or individual
 *
 * OpenAPI spec version: 4.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */
/* eslint-disable no-param-reassign,dot-notation,prefer-template */

import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import IHttpClient from '../../IHttpClient';
import { IAPIConfiguration } from '../../IAPIConfiguration';
import { Headers } from '../../Headers';
import HttpResponse from '../../HttpResponse';
import IFilter from '../../../types/IFilter';
import HttpClient from '../../HttpClient';
import MasterConfigService from '../../master/api/MasterConfigService';
import client from '../../../common/AjaxClient';
import { HttpMethods } from '../../../types/CommonTypes';

/* eslint-disable no-param-reassign,no-case-declarations,dot-notation,lines-between-class-members,prefer-const,prefer-template */

export default class MinioService {
    private APIConfiguration: IAPIConfiguration;
    masterService = new MasterConfigService();
    private httpClient: IHttpClient;

    constructor() {
        this.APIConfiguration = {
            basePath: ''
        };
        try {
            this.masterService
                .getServiceUrl('MINIO_URL')
                .subscribe((url) => (this.APIConfiguration.basePath = url));
        } catch (e) {
            console.log('error while fetching basePath url', e);
        }
        this.httpClient = new HttpClient();
    }


    public deleteMinioData(
        bucketName: any,
        uuid: any,
        idType: any,
        observe: any = 'body',
        headers: Headers = {}
    ): Observable<any> {
        if (!bucketName || !uuid || !idType) {
            throw new Error(
                'Required parameter was null or undefined when calling deleteMinioData.'
            );
        }

        headers['Accept'] = 'application/json;charset=utf-8';

        const response: Observable<HttpResponse<any>> = this.httpClient.delete(
            `${this.APIConfiguration.basePath
            }/delete/${bucketName}/${encodeURIComponent(
                String(uuid)
            )}/${idType}` as any,
            headers
        );
        if (observe === 'body') {
            return response.pipe(map((httpResponse) => httpResponse.response));
        }
        return response;
    }

    public downloadFile(
        fileName: any,
        headers: Headers = { 'Content-Type': 'multipart/form-data' }
    ): Promise<any> {
        headers.Accept = 'application/json;charset=utf-8';
        headers['x-auth-token'] =
            'VQ/ZK9+z2gzgTOm1ZnMyn0Ev6byXWPqWgsj1TrbN74c=';
        return client(
            `${this.APIConfiguration.basePath}/download/${fileName}`,
            HttpMethods.GET,
            undefined,
            false
        );
    }
}
