/**
 * API GeographicLocation
 * ## TMF API Reference : TMF 675 - Geographic Location ### Release : 17.5 - January 2018  The geographic location API provides a standardized client interface to a location management system. A Geographic Location is a point, a surface or a volume defined by geographic point(s). These points should be associated with an accuracy and a spatial reference.  ### Resources - GeographicLocation - RetrieveGeographicLocation - RetrieveLocationRelation - Hub  ### Operations Geographic Location API performs the following operations : - Retrieve a geographic location or a collection of geographic locations - Retrieve a retrieve geographic location or a collection of retrieve geographic locations - Create a retrieve geographic location - Retrieve a retrieve location relation or a collection of retrieve location relations - Create a retrieve location relation - Notify events on these resources
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {GeographicLocationReferred} from './geographicLocationReferred';
import {ModelObject} from './modelObject';

/**
 * This resource is used to manage the request and response to retrieve a thing (any object)
 */
export interface RetrieveGeographicLocation {
    /**
     * Unique identifier of the retrieve task
     */
    id?: string;
    /**
     * An URI used to access to the task resource
     */
    href?: string;
    /**
     * Status of the task (inProgress, terminatedWithErrror, done)
     */
    status?: string;
    /**
     * Requested accuracy of the retrieval
     */
    requestedAccuracy?: number;
    /**
     * Timestamp of end of task execution
     */
    time?: Date;
    thing: ModelObject;
    geographicLocation?: GeographicLocationReferred;
}
