/**
 * Cash Register Management API
 * APIs to manage Cash Register
 *
 * OpenAPI spec version: 1.6.10
 * Contact: yagyawal.thakur@comviva.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Error object returned in REST API Response in case of error.
 */
export interface ModelError { 
    /**
     * Response Code  (400 = Invalid request, 404= Not found, 500 = System error, etc)
     */
    code: number;
    /**
     * Error message associated with the error code.
     */
    response: string;
}
