/**
 *
 *
 *
 *
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Observable} from 'rxjs';
import {map} from 'rxjs/operators';
import IHttpClient from '../../IHttpClient';
import {IAPIConfiguration} from '../../IAPIConfiguration';
import {Headers} from '../../Headers';
import HttpResponse from '../../HttpResponse';
import HttpClient from '../../HttpClient';
import MasterConfigService from '../../master/api/MasterConfigService';
import {VisitMaster} from '../model/VisitMaster';
import IFilter from 'src/types/IFilter';

/* eslint-disable no-param-reassign */

export default class StockNormService {
    APIConfiguration: IAPIConfiguration;

    masterService = new MasterConfigService();

    httpClient: IHttpClient;

    constructor() {
        this.APIConfiguration = {
            basePath: ''
        };
        try {
            this.masterService
                .getServiceUrl('VISIT_URL')
                .subscribe((url) => (this.APIConfiguration.basePath = url));
        } catch (e) {
            console.log('error while fetching visit url', e);
        }
        this.httpClient = new HttpClient();
    }

    /**
     * Get customer information for a given accountID
     * Get customer information for a given accountID
     * @param serviceID Get customer information for a given accountID
     @param queryString
     @param headers
     */

    public getVisits(
        queryString: string,
        headers: Headers = {}
    ): Observable<any> {
        if (!queryString) {
            throw new Error(
                'Required parameter limit and offset was null or undefined when calling getInventoryDetails.'
            );
        }
        headers.Accept = 'application/json;charset=utf-8';
        headers['x-auth-token'] =
            'VQ/ZK9+z2gzgTOm1ZnMyn0Ev6byXWPqWgsj1TrbN74c=';
        const response: Observable<HttpResponse<VisitMaster>> =
            this.httpClient.get(
                `${this.APIConfiguration.basePath}/${queryString}`,
                headers
            );
        return response.pipe(map((d) => d.response));
    }

    public createVisits(
        body: VisitMaster,
        headers: Headers = {}
    ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error(
                'Required parameter body was null or undefined when calling createInventory.'
            );
        }

        headers.Accept = 'application/json;charset=utf-8';
        headers['x-auth-token'] =
            'VQ/ZK9+z2gzgTOm1ZnMyn0Ev6byXWPqWgsj1TrbN74c=';
        const response: Observable<HttpResponse<VisitMaster>> =
            this.httpClient.post(
                `${this.APIConfiguration.basePath}/visits/master`,
                body,
                headers
            );
        return response.pipe(map((d) => d.response));
    }

    /**
     * Deletes a stock Norm
     * This operation deletes a Stock Norms entity.
     * @param id Identifier of the Stock Norm
     */

    deleteVisits(
        id: string,
        observe: any = 'body',
        headers: Headers = {}
    ): Observable<any> {
        if (!id) {
            throw new Error(
                'Required parameter id was null or undefined when calling delete StockNorms.'
            );
        }

        headers.Accept = 'application/json;charset=utf-8';

        const response: Observable<HttpResponse<any>> = this.httpClient.delete(
            `${this.APIConfiguration.basePath}/visits/master/${id}`,
            headers
        );
        if (observe === 'body') {
            return response.pipe(map((httpResponse) => httpResponse.response));
        }
        return response;
    }

    /**
     * Updates partially an Inventory
     * This operation updates partially an Inventory entity.
     * @param inventorySkuOfferId Identifier of the Inventory
     * @param Inventory The Inventory to be updated
     */

    editVisits(
        id: string,
        body: VisitMaster,
        observe: any = 'body',
        headers: Headers = {}
    ): Observable<any> {
        if (!id) {
            throw new Error(
                'Required parameter id was null or undefined when calling delete Inventory.'
            );
        }

        headers.Accept = 'application/json;charset=utf-8';

        const response: Observable<HttpResponse<any>> = this.httpClient.patch(
            `${this.APIConfiguration.basePath}/visits/master/${id}`,
            body,
            headers
        );
        if (observe === 'body') {
            return response.pipe(map((httpResponse) => httpResponse.response));
        }
        return response;
    }

    public listVisits(
        fields?: string,
        offset?: number,
        limit?: number,
        observe: any = 'body',
        headers: Headers = {},
        filters?: IFilter[]
    ): Observable<any> {
        let queryParameters: string[] = [];
        if (fields !== undefined) {
            queryParameters.push(
                'fields=' + encodeURIComponent(String(fields))
            );
        }
        if (offset !== undefined) {
            queryParameters.push(
                'offset=' + encodeURIComponent(String(offset))
            );
        }
        if (limit !== undefined) {
            queryParameters.push('limit=' + encodeURIComponent(String(limit)));
        }
        if (filters !== undefined) {
            filters.forEach((filter: IFilter) => {
                queryParameters.push(
                    `${filter.key}${
                        filter.operator === 'eq' ? '*=' : filter.operator
                    }${encodeURIComponent(String(filter.value))}`
                );
            });
        }

        headers['Accept'] = 'application/json;charset=utf-8';

        const response: Observable<HttpResponse<Array<VisitMaster>>> =
            this.httpClient.get(
                `${
                    this.APIConfiguration.basePath
                }/visits/master?${queryParameters.join('&')}` as any,
                headers
            );
        if (observe === 'body') {
            return response.pipe(map((httpResponse) => httpResponse.response));
        }
        return response;
    }

    // public listVisits(
    //     fields?: string,
    //     offset?: number,
    //     limit?: number,
    //     observe: any = 'body',
    //     headers: Headers = {}
    // ): Observable<any> {
    //     headers.Accept = 'application/json;charset=utf-8';

    //     const response: Observable<HttpResponse<Array<VisitMaster>>> =
    //         this.httpClient.get(
    //             `${this.APIConfiguration.basePath}/visits/master?` as any,
    //             headers
    //         );
    //     if (observe === 'body') {
    //         return response.pipe(map((httpResponse) => httpResponse.response));
    //     }
    //     return response;
    // }
}
